/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package array3;

/**
 *
 * @author Khofi Muffin
 */
public class Arr3 extends javax.swing.JFrame {
     int a, b, c, d, tambah, kurang, kali, bagi;

    
    
    /**
     * Creates new form Arr3
     */
    public Arr3() {
        initComponents();
            b1.setVisible(false);
            b2.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(false);
            bil2.setVisible(false);
            bil3.setVisible(false);
            bil4.setVisible(false);
            jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        arit = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        b2 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        bil4 = new javax.swing.JTextField();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        jumbil = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        kotak = new javax.swing.JTextField();
        apa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 150, 30);

        arit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        arit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aritActionPerformed(evt);
            }
        });
        getContentPane().add(arit);
        arit.setBounds(220, 50, 170, 20);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setLayout(null);

        b2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b2.setText("Bilangan 2");
        jPanel1.add(b2);
        b2.setBounds(50, 150, 110, 30);

        b1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b1.setText("Bilangan 1");
        jPanel1.add(b1);
        b1.setBounds(50, 110, 110, 30);

        b3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b3.setText("Bilangan 3");
        jPanel1.add(b3);
        b3.setBounds(50, 190, 110, 30);

        b4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b4.setText("Bilangan 4");
        jPanel1.add(b4);
        b4.setBounds(50, 230, 110, 30);
        jPanel1.add(bil4);
        bil4.setBounds(200, 230, 170, 30);
        jPanel1.add(bil1);
        bil1.setBounds(200, 110, 170, 30);
        jPanel1.add(bil2);
        bil2.setBounds(200, 150, 170, 30);
        jPanel1.add(bil3);
        bil3.setBounds(200, 190, 170, 30);

        jumbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "2", "3", "4" }));
        jumbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumbilActionPerformed(evt);
            }
        });
        jPanel1.add(jumbil);
        jumbil.setBounds(200, 70, 170, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Jumlah Bilangan");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 60, 150, 40);

        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel1.add(hitung);
        hitung.setBounds(150, 270, 110, 23);
        jPanel1.add(kotak);
        kotak.setBounds(40, 310, 330, 80);

        apa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(apa);
        apa.setBounds(150, 20, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 80, 420, 410);

        setBounds(0, 0, 477, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here
        Proses();
    }//GEN-LAST:event_hitungActionPerformed

    private void aritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aritActionPerformed
        // TODO add your handling code here:
        if(arit.getSelectedItem().equals("Penjumlahan")){
            apa.setText("Penjumlahan");
            jPanel1.setVisible(true);
        }
        else if(arit.getSelectedItem().equals("Pengurangan")){
            apa.setText("PENGURANGAN");
            jPanel1.setVisible(true);
        }
        else if(arit.getSelectedItem().equals("Perkalian")){
            apa.setText("PERKALIAN");
            jPanel1.setVisible(true);
        }
        else if(arit.getSelectedItem().equals("Pembagian")){
            apa.setText("PEMBAGIAN");
            jPanel1.setVisible(true);
        }
        else{
            apa.setText(" ");
            jPanel1.setVisible(false);
        }
    }//GEN-LAST:event_aritActionPerformed

    private void jumbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumbilActionPerformed
        // TODO add your handling code here:
        if(jumbil.getSelectedItem().equals("2")){
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(false);
            bil4.setVisible(false);
        }
        else if(jumbil.getSelectedItem().equals("3")){
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
        }
        else if(jumbil.getSelectedItem().equals("4")){
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
        }
        else{
            b1.setVisible(false);
            b2.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(false);
            bil2.setVisible(false);
            bil3.setVisible(false);
            bil4.setVisible(false);
        }
    }//GEN-LAST:event_jumbilActionPerformed

    private void Proses(){
        
        a = Integer.parseInt(bil1.getText());
        b = Integer.parseInt(bil2.getText());
        c = Integer.parseInt(bil3.getText());
        d = Integer.parseInt(bil4.getText()); 
        
        if(arit.getSelectedItem().equals("Penjumlahan")){
            if(jumbil.getSelectedItem().equals("2")){
                tambah = a+b;
                kotak.setText("Penjumlahan dari " +a+ " + " +b+ " = " +tambah);
            }
            if(jumbil.getSelectedItem().equals("3")){
                tambah = a+b+c;
                kotak.setText("Penjumlahan dari "+a+" + "+b+" + "+c+" = "+tambah);
            }
            if(jumbil.getSelectedItem().equals("4")){
                tambah = a+b+c+d;
                kotak.setText("Penjumlahan dari "+a+" + "+b+" + "+c+" + "+d+" = "+tambah);
            }
        }
        
        else if(arit.getSelectedItem().equals("Pengurangan")){
            if(jumbil.getSelectedItem().equals("2")){
                kurang = a-b;
                kotak.setText("Pengurangan dari "+a+" - "+b+" = "+kurang);
            }
            if(jumbil.getSelectedItem().equals("3")){
                kurang = a-b-c;
                kotak.setText("Pengurangan dari "+a+" - "+b+" - "+c+" = "+kurang);
            }
            if(jumbil.getSelectedItem().equals("4")){
                kurang = a-b-c-d;
                kotak.setText("Pengurangan dari "+a+" - "+b+" - "+c+" - "+d+" = "+kurang);
            }
        }
        
        else if(arit.getSelectedItem().equals("Perkalian")){
            if(jumbil.getSelectedItem().equals("2")){
                kali = a*b;
                kotak.setText("Perkalian dari "+a+" x "+b+" = "+kali);
            }
            if(jumbil.getSelectedItem().equals("3")){
                kali = a*b*c;
                kotak.setText("Perkalian dari "+a+" x "+b+" x "+c+" = "+kali);
            }
            if(jumbil.getSelectedItem().equals("4")){
                kali = a*b*c*d;
                kotak.setText("Perkalian dari "+a+" x "+b+" x "+c+" x "+d+" = "+kali);
            }
        }
        
        else if(arit.getSelectedItem().equals("Pembagian")){
            if(jumbil.getSelectedItem().equals("2")){
                bagi = a/b;
                kotak.setText("Pembagian dari "+a+" : "+b+" = "+bagi);
            }
            if(jumbil.getSelectedItem().equals("3")){
                bagi = a/b/c;
                kotak.setText("Pembagian dari "+a+" : "+b+" : "+c+" = "+bagi);
            }
            if(jumbil.getSelectedItem().equals("4")){
                bagi = a/b/c/d;
                kotak.setText("Pembagian dari "+a+" : "+b+" : "+c+" : "+d+" = "+bagi);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arr3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arr3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arr3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arr3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arr3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apa;
    private javax.swing.JComboBox<String> arit;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jumbil;
    private javax.swing.JTextField kotak;
    // End of variables declaration//GEN-END:variables
}
